### ISSUE TITLE
[Bug]: console - cannot use standalone: composer, missing cache and class already in use

### ISSUE THREAD

**Issue by homersimpsons** [tempestphp/tempest-framework#601]
### Tempest Version

dev-main

### PHP Version

8.3

### Operating System

Linux

### Description

I want to setup a console application, following https://tempestphp.com/docs/console/getting-started/

I run `composer require tempest/console:dev-main` and create a `main.php` file and an `src/InteractiveCommand` with the correct psr-4 setup et al.

### 1. Missing `tempest/cache`

I try to run `php ./main.php` and have the following error:
```
Trait "Tempest\Cache\IsCache" not found

at vendor/tempest/core/src/DiscoveryCache.php:16
// ....
```

So I install the cache component: `composer require tempest/cache`

### 2. Class already in use

Once the cache is installed, I re-run the application with `php ./main.php`, now I have the following error:
```
Cannot declare class App\InteractiveCommand, because the name is already in use

at src/InteractiveCommand.php:8
```

It looks like the component tries to load my class twice (maybe once for discovery and once tu run it?)

Note that I also tried with `composer require tempest/console:1.0-alpha2` that lead to the same result.

### 3. Composer instructions

The instruction at https://tempestphp.com/console/ suggest to run `composer require tempest/console --stability alpha`, but this fails with composer 2.53 as 'The "--stability" option does not exist.'

I am not sure what is incorrect here. The framework looks really promising!

### Steps to Reproduce

1. `composer require tempest/console:dev-main`
2. (copy the files)
3. `composer require tempest/cache` (first issue)
4. `php ./main.php` (second issue)

**Comment by aidan-casey** [comment]
Ah... this looks a like a combination of a true bug and some documentation errors. Thank you for reporting!

I do think you might find success with trying `composer require tempest/console:1.0-alpha1` in the meantime.

**Comment by homersimpsons** [comment]
> Ah... this looks a like a combination of a true bug and some documentation errors. Thank you for reporting!

Yes, I was not sure if I should have opened multiple issues.

> I do think you might find success with trying `composer require tempest/console:1.0-alpha1` in the meantime.

I tried, in fact I do not have the cache issue (1), but I still have the duplicate class issue (2)

**Comment by brendt** [comment]
Fixed with #603 (dev-main)

**Comment by homersimpsons** [comment]
> Fixed with #603 (dev-main)

I will try this today, but I do not think that this will fix the second issue about duplicate class. Should I open a new issue for this? Or should I re-open this one?

**Comment by homersimpsons** [comment]
So I tried with `composer require tempest/console:dev-main`, I n o longer have the `tempest/cache` issue. But I still have the second issue: the class is seen as declared twice.

**Comment by brendt** [comment]
Could you maybe push your repo somewhere for me to take a look? I did test this, and couldn't reproduce it after my fix. But maybe I missed something.
